package demo.ai.analytical.agent.telegrambot.statemachine;

public enum BotEvent {

    RESIEVED_START_COMMAND_EVENT,
    RESIEVED_HELP_COMMAND_EVENT,
    RESIEVED_STOP_COMMAND_EVENT,
    RESIEVED_INN_COMMAND_EVENT,
    RESIEVED_CONTRACT_COMMAND_EVENT,

    RESIEVED_INN_VALUE_EVENT,
    RESIEVED_REG_NUMBER_VALUE_EVENT,
    RESIEVED_QUESTION_VALUE_EVENT,

    RESIEVED_NO_NEED_CONTRACT_ANALYSIS_EVENT,
    RESIEVED_NEED_CONTRACT_ANALYSIS_EVENT,
    RESIEVED_NO_NEED_ADDITIONAL_INFO_EVENT,
    RESIEVED_NEED_ADDITIONAL_INFO_EVENT

}
